# config/packages/monolog.yaml
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            formatter: monolog.formatter.line  # Usamos el formateador predefinido en services.yaml
            process_psr_3_messages: false

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
