# config/services.yaml
parameters:
    # Parámetros adicionales si se necesitan

services:
    # Definición del formateador personalizado para Monolog
    monolog.formatter.line:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
            - true  # Incluir trazas de pila si es necesario

    # Definición del procesador IntrospectionProcessor de Monolog
    monolog.processor.introspection:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }  # Aplica el procesador globalmente
