# TrytonBot/config/services.yaml
parameters:
    # Define aquí parámetros adicionales si es necesario

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\BotManService:
        arguments:
            $responsePatterns:
                - '@App\Service\GreetingPattern'
                - '@App\Service\FallbackPattern'
            $logger: '@logger'

    App\Service\GreetingPattern:
        arguments:
            $logger: '@logger'

    App\Service\FallbackPattern:
        arguments:
            $logger: '@logger'

    App\Service\ReplyCollector:
        autowire: true
        autoconfigure: true

    App\Controller\ChatController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\BotController:
        public: true

    monolog.formatter.line:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%extra.index%%] %%channel%%.%%level_name%%: \"%%extra.file%%:%%extra.line%%\" - %%message%% - %%context%%\n"
            - true

    App\Monolog\Processor\LogIndexProcessor:
        tags:
            - { name: monolog.processor }

    # Keep only one definition of monolog.processor.introspection
    monolog.processor.introspection:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }  # Aplica el procesador globalmente
