# config/services.yaml
parameters:
    # Parámetros adicionales si se necesitan

services:
    # Definición del formateador personalizado para Monolog
    monolog.formatter.line:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
            - true  # Incluir trazas de pila si es necesario

    # Definición del procesador IntrospectionProcessor de Monolog
    monolog.processor.introspection:
        class: Monolog\Processor\IntrospectionProcessor
        tags:
            - { name: monolog.processor }  # Aplica el procesador globalmente

    App\Controller\ChatController:
        autowire: true
        autoconfigure: true
        public: true  # Asegura que esté accesible públicamente como controlador

    App\Service\BotManService:
        autowire: true    # Permite que Symfony resuelva automáticamente las dependencias internas
        autoconfigure: true # Registra automáticamente el servicio
        public: true      # Asegura que esté disponible para otros servicios

    App\Controller\BotController:
        autowire: true
        autoconfigure: true
        public: true
