# TrytonBot/config/services.yaml
parameters:
    # Define aquí parámetros adicionales si es necesario

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\BotManService:
        arguments:
            $responsePatterns:
                - '@App\Service\GreetingPattern'
                - '@App\Service\FallbackPattern'
            $logger: '@logger'

    App\Service\GreetingPattern:
        arguments:
            $logger: '@logger'

    App\Service\FallbackPattern:
        arguments:
            $logger: '@logger'

    App\Service\ReplyCollector:
        autowire: true
        autoconfigure: true

    App\Controller\ChatController:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\BotController:
        public: true

    monolog.formatter.line:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%extra.index%%] | %%extra.channel_level%% | \"%%extra.file_line%%\" | %%message%% | %%context%%\n"
            - true

    App\Monolog\Processor\LogIndexProcessor:
        tags:
            - { name: monolog.processor }

    App\Monolog\Processor\CustomIntrospectionProcessor:
        tags:
            - { name: monolog.processor }

    monolog.processor.introspection:
        class: App\Monolog\Processor\CustomIntrospectionProcessor
        tags:
            - { name: monolog.processor }

    App\Monolog\Processor\FixedLengthProcessor:
        tags:
            - { name: monolog.processor }

