# config/services.yaml

parameters:
    # Define aquí parámetros adicionales si es necesario

services:
    # Configuración predeterminada para los servicios en este archivo
    _defaults:
        autowire: true      # Inyecta dependencias automáticamente en tus servicios.
        autoconfigure: true # Registra automáticamente tus servicios como comandos, suscriptores de eventos, etc.

    # Hace que las clases en src/ estén disponibles como servicios
    # Esto crea un servicio por clase cuyo id es el nombre de la clase completamente calificado
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Definición explícita de servicios adicionales si es necesario
    App\Service\BotManService:
        arguments:
            $responsePatterns:
                - '@App\Service\GreetingPattern'
                - '@App\Service\FallbackPattern'
            $logger: '@logger'  # Inyección del logger como dependencia

    App\Service\GreetingPattern:
        arguments:
            $logger: '@logger'  # Inyección del logger en el servicio de patrón de saludo

    App\Service\FallbackPattern:
        arguments:
            $logger: '@logger'  # Inyección del logger en el servicio de patrón de respuesta predeterminada

    App\Service\ReplyCollector:
        autowire: true
        autoconfigure: true
